//THIS DUMMY DATA IS COURTESY OF LLAMA DEV WHOSE GIT REPO I SOURCED IT FROM. LINK: https://github.com/safak/youtube/tree/react-social-ui

export const Users = [
  {
    id: 1,
    profilePicture: "Profile pics/1.jpg",
    username: "Chris Redfield",
  },
  {
    id: 2,
    profilePicture: "Profile pics/2.jpg",
    username: "Barry Burton",
  },
  {
    id: 3,
    profilePicture: "Profile pics/3.jpg",
    username: "Claire Redfield",
  },
  {
    id: 4,
    profilePicture: "Profile pics/ada prof pic.jpg",
    username: "Ada Wong",
  },
  {
    id: 5,
    profilePicture: "Profile pics/Leon prof pic.jpg",
    username: "Leon S. Kennedy",
  },
  {
    id: 6,
    profilePicture: "Profile pics/ashley prof pic.png",
    username: "Ashley Graham",
  },
  {
    id: 7,
    profilePicture: "Profile pics/7.jpg",
    username: "Jill Valentine",
  },
  {
    id: 8,
    profilePicture: "Profile pics/8.jpg",
    username: "Ethan Winters",
  },
  {
    id: 9,
    profilePicture: "Profile pics/9.jpg",
    username: "Albert Wesker",
  },
  {
    id: 10,
    profilePicture: "Profile pics/8.jpg",
    username: "Ethan Winters",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "posts/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Residence of evil",
    photo: "posts/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "posts/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    desc: "Who even took this photo?!",
    photo: "posts/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    desc: "bit of a tight spot",
    photo: "posts/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "posts/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "posts/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    desc: "Real nice folk living around these parts",
    photo: "posts/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "posts/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "posts/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
